<?php echo $this->doctype(), PHP_EOL; ?>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
<head>
<base href="http://<?php echo $_SERVER['SERVER_NAME'] . $this->baseUrl();?>/" />
<?php
    echo $this->headTitle('Error'), PHP_EOL .
        $this->headMeta(), PHP_EOL .
        $this->headLink()->appendStylesheet('/themes/default/css/main.css'), PHP_EOL .
		$this->headLink()->appendStylesheet('/themes/default/css/color.css'), PHP_EOL .
        $this->headScript(), PHP_EOL .
        $this->jQuery(), PHP_EOL;
?>
</head>
<body>
<div id="wrapperOuter">
    <div id="wrapperInner">

        <div id="header">
	        <div id="siteTitle">
		        <a href="<?php echo $this->url(array(), 'home');?>" title="i-PMS"><span>i-PMS</span></a>
	        </div>

            <div id="navigation">
                <ul>
                    <li class="active"><a href="/"><span>Home</span></a></li>
                    <!--<li><a href="#"><span>Bug Tracker</span></a></li>
                    <li><a href="#"><span>Timeline</span></a></li>
                    <li><a href="#"><span>Forum</span></a></li>
                    <li><a href="#"><span>Download</span></a></li>
                    <li><a href="#"><span>3rd Packages</span></a></li>
                    <li><a href="#"><span>Documentation</span></a></li>
                    <li><a href="#"><span>Contact</span></a></li>-->
                </ul>
            </div>
	        <div id="siteDescription">Another control panel for virtual hosting management...</div>
        </div>

		<div id="location">
			<div id="breadcrumbs">
				<span><?php echo $this->translate('You are here');?>:</span>
				<a href="<?php echo $this->url(array(), 'home');?>" title="<?php echo $this->translate('Home page');?>"><span><?php echo $this->translate('Home');?></span></a>
			</div>
			<div id="loginContainer">
			<?php if ($this->user()->isLogged()):?>
				<a class="userSmallIcon smallIcon"  href="<?php echo $this->baseUrl().'/users/show/id/'.$this->user()->id;?>" title="<?php echo $this->translate('Show profile');?>">
					<span><?php echo $this->escape($this->user()); ?></span>
				</a>
				<span>-</span>
				<a class="logoutSmallIcon smallIcon" href="<?php echo $this->url(array(), 'logout');?>" title="<?php echo $this->translate('Logout'); ?>">
					<span><?php echo $this->translate('Logout');?></span>
				</a>
			<?php else:?>
				<a href="<?php echo $this->url(array(), 'login');?>?from=<?php echo $this->url();?>" title="<?php echo $this->translate('Login');?>"><span><?php echo $this->translate('Login');?></span></a>
				<span>|</span>
				<a href="#" title="<?php echo $this->translate('Lost Password');?>">
					<span><?php echo $this->translate('Lost Password');?></span>
				</a>
			<?php endif;?>
			</div>
		</div>
        <div id="page">
            <div id="content">
                <?php echo $this->layout()->content;?>
            </div>
            <div id="sidebar">
                <?php //echo $this->Widgets('sidebar', array('Login', 'RecentComments'));?>
                <?php //echo $this->Widgets()->sidebar('sidebar', array('Login'));?>
            </div>
            <div class="clearer"></div>
        </div>
    </div>
</div>
<div id="footer">
    <!--<img id="footerImageLeft" src="/themes/default/images/powered_zend_framework.png" alt="Powered by Zend Framework" />-->
    <ul>
        <li class="first"><a href="#"><span>About</span></a></li>
        <li><a href="#"><span>Contact</span></a></li>
        <li><a href="#"><span>Faq</span></a></li>
        <li><a href="#"><span>Terms</span></a></li>
        <li><a href="#"><span>Privacy</span></a></li>
    </ul>
    <p>&copy; 2010 - 2011 i-MSCP Team. All Rights Reserved. - Site by Laurent Declercq</p>
</div>
</body>
</html>
