<?php $this->headTitle($this->translate('Edit Post') . ': ' . $this->escape($this->form->getValue('title')));?>

<h1><?php echo $this->translate('Edit Post'); ?></h1>
<?php echo $this->form; ?>

<a  href="<?php echo $this->url(array('pid' => $this->form->getValue('pid')), 'post_show');?>" title="<?php echo $this->translate('Abort');?>">
	<strong><?php echo $this->translate('Abort');?></strong>
</a>
