<?php $this->headTitle($this->translate('Edit post') . ': ' . $this->escape($this->form->getValue('title')));?>

<div class="post">
    <h2><?php echo $this->translate('Edit post'); ?></h2>
    <?php echo $this->form; ?>
    <div class="clearer"></div>
</div>

<p class="backLink">
    <a href="<?php echo $this->url(array('pid' => $this->form->getValue('pid')), 'post_show');?>"
       title="<?php echo $this->translate('Abort');?>">
        <strong><?php echo $this->translate('Abort');?></strong>
    </a>
</p>
