<h1><?php echo $this->translate('Posts');?></h1>

<?php if (count($this->paginator)):
    foreach ($this->paginator as $post):
?>
<div id="post-<?php echo $post['pid'];?>" class="post post-<?php echo $post['pid'];?>">
    <h2 class="entryTitle">
        <a href="<?php echo $this->url(array('pid' => $post['pid']), 'post_show');?>"
           title="<?php echo $this->translate('Read more...');?>"><?php echo $this->escape($post['title']);?></a>
    </h2>
    <p class="entryMeta">
        <?php printf($this->translate('Posted on %s, by '), date('F d, Y', $post['created_on']))?>
        <a href="#" title="view profile"><?php echo $post['username'];?></a>
    </p>
    <div class="entryDescription">
		<?php echo $post['teaser'];?>
    </div>
    <div class="entryUtility">
		<span><?php echo $this->translate('Posted in');?></span>
		<a href="<?php echo $this->baseUrl() . '/categories/view/' . $post['category'];?>" title="<?php echo $this->translate('View categorie');?>"><?php echo ucfirst($post['category']);?></a>
		<span>|</span>
		<a href="#" title="Comments"><?php printf('%s Comments', $post['comments_count']);?></a>
		<span>|</span>
		<a href="#" title="Edit post"><?php echo $this->translate('Edit');?></a>
		<a href="<?php echo $this->url(array('pid' => $post['pid']), 'post_show');?>" title="<?php echo $this->translate('Read more...');?>"><?php echo $this->translate('Read more...');?></a>
        <div class="clearer"></div>
    </div>
</div>
<br />
<?php endforeach;
 if(count($this->paginator) > 1):
?>
<div id="paginationOuter">
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml');?>
</div>
<?php endif;
else:?>
<div class="note">
	<?php echo $this->translate('Sorry but there are currently no posts');?>
</div>
<?php endif;?>
