<h1><?php echo $this->translate('Posts');?></h1>

<?php if (count($this->paginator)):
    foreach ($this->paginator as $post):
?>
<div class="post">
    <h2>
        <a href="<?php echo $this->url(array('pid' => $post['pid']), 'post_show');?>"
           title="<?php echo $this->translate('Read more...');?>"><?php echo $this->escape($post['title']);?></a>
    </h2>
    <p style="color:#666;">
        <?php printf($this->translate('Posted on %s, by '), date('F d, Y', strtotime($post['created_at'])))?>
        <a style="color:#666;" href="#" title="view profile"><?php echo $post['username'];?></a>
    </p>
    <div class="postBody">
        <div class="teaser" style="margin-top:16px;">
            <?php echo $post['teaser'];?>
        </div>
    </div>
    <div style="margin-top:20px;">
        <div style="float:left;color:#666;">
            <span><?php echo $this->translate('Posted in');?></span>
            <a style="color:#666;" href="<?php echo $this->baseUrl() . '/categories/view/' . $post['categorie'];?>"
                title="<?php echo $this->translate('View categorie');?>"><?php echo ucfirst($post['categorie']);?></a>
            <span>|</span>
            <a style="color:#666;" href="#" title="Comments"><?php printf('%s Comments', $post['comments_count']);?></a>
            <span>|</span>
            <a style="color:#666;" href="#" title="Edit post"><?php echo $this->translate('Edit');?></a>
        </div>
        <div style="float:right;">
            <a href="<?php echo $this->url(array('pid' => $post['pid']), 'post_show');?>"
                title="<?php echo $this->translate('Read more...');?>"><?php echo $this->translate('Read more...');?></a>
        </div>
        <div class="clearer"></div>
    </div>
</div>
<br />
<?php endforeach;
 if(count($this->paginator) > 1):
?>
<div id="paginationOuter">
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml');?>
</div>
<?php endif;
else:?>
<div class="note">
	<?php echo $this->translate('Sorry but there are currently no posts');?>
</div>
<?php endif;?>
