<?php $this->headTitle($this->translate('Post') . ': ' .$this->escape($this->post['title']));?>

<div class="post">
    <h1><?php echo $this->escape($this->post['title']);?></h1>
    <div class="subTitle">
    	<span class="fastLinks">
    	    <a href="<?php echo $this->url(array('pid' => $this->post['pid']), 'post_edit');?>"
               class="editSmallIcon smallIcon"
               title="<?php echo $this->translate('Edit post');?>"
            >
            <span><?php echo $this->translate('Edit');?></span></a><span> - </span>
    	    <a href="<?php echo $this->url(array('pid' => $this->post['pid']), 'post_delete');?>"
               class="deleteSmallIcon smallIcon"
               title="<?php echo $this->translate('Delete post');?>"
            >
                <span><?php echo $this->translate('Delete');?></span>
            </a>
    	</span>
    	<span>
			<?php printf($this->translate('Posted on %s by '), date('F d, Y', $this->post['created_on']));?>
            <a href="#" title="<?php echo $this->translate('View user profile');?>">
                <span>
                <?php
                    if(null != $this->post['lastname'] && null != $this->post['firstname']) {
						$this->escape(printf('%s %s', $this->post['lastname'], $this->post['firstname']));
                    } elseif(null != $this->post['username']) {
                        echo $this->escape($this->post['username']);
                    } else {
	                    echo $this->translate('Unregistered user');
                    }
                ?>
		    </span>
        </a>
	</span>
    </div>
    <div class="postBody">
        <div class="postTeaser" style="border:1px solid #666;padding:5px;background-color:#E3E7F0;border-radius:8px;">
            <?php echo $this->escape($this->post['teaser']);?>
        </div>
	    <div class="postContent" style="margin-top:20px;font-family:trebuchet">
            <?php echo $this->post['body'];?>
		</div>
    </div>
</div>

<?php
	echo $this->action('index', 'comments', 'Comment', array('pid' => $this->post['pid']));
	if($this->post['allow_comments']) echo $this->action('add', 'comments', 'Comment');
?>
