<div class="navlinks" style="margin-top:20px;font-weight:bold;font-size:1.2em;">
	<a href="<?php echo $this->url(array(), 'forum_index');?>"
	   title="<?php echo $this->translate('Forums list');?>"><?php echo $this->translate('Forums');?></a>
	-
	<a href="<?php echo $this->url(array('fid' => $this->forum['fid']), 'forum_show');?>"
	   title="<?php echo $this->escape($this->forum['name']);?>"><?php echo $this->escape($this->forum['name']);?></a>
	-
	<?php echo $this->translate('New Thread');?>
</div>
<div>
	<?php echo $this->form;?>
</div>
