<h1>
	<a href="<?php echo $this->url(array(), 'forum_index');?>" title="<?php echo $this->translate('Forums list');?>"><?php echo $this->translate('Forums');?></a>
	<span>-</span>
	<a href="<?php echo $this->url(array('fid' => $this->forum['fid']), 'forum_show');?>" title="<?php echo $this->escape($this->forum['name']);?>"><?php echo $this->escape($this->forum['name']);?></a>
	<span>-</span>
	<span><?php echo $this->translate('New Thread');?></span>
</h1>
<?php echo $this->form;?>
