<h1>
	<a href="<?php echo $this->url(array(), 'forum_index');?>" title="<?php echo $this->translate('Forums list');?>"><?php echo $this->translate('Forums');?></a>
	<span>/</span>
	<a href="<?php echo $this->url(array('fid' =>$this->forum['fid']), 'forum_show');?>"  title="<?php echo $this->escape($this->forum['name']);?>"><?php echo $this->escape($this->forum['name']);?></a>
	<span>/</span>
	<span><?php echo $this->escape($this->thread['subject']);?></span>
</h1>

<table>
	<tr>
		<th colspan="2">
			<div>
				<strong><?php echo $this->escape($this->forum['name']);?></strong>
			</div>
		</th>
	</tr>
	<tr>
		<th><?php echo $this->translate('Author');?></th>
		<th><?php echo $this->translate('Message');?></th>
	</tr>
	<?php $i = 1; foreach($this->posts as $post):?>
	<tr class="<?php echo $this->cycle(array('odd', 'even'))->next();?>" id="pid<?php echo $post['pid'];?>">
		<td style="white-space: nowrap; text-align: center;" valign="top" width="15%">
		<strong>
			<span class="largetext"><a href="#"><em><?php echo ucfirst($post['username']);?></em></a></span>
		</strong>
		<!--<img src="" title="Offline" alt="Offline">-->
		<br>
		<span class="smalltext">
			Administrator
			<br />
			<?php echo $this->translate('Posts');?>: 2
			<br />
			<?php echo $this->translate('Joined on');?>: Feb 2011
		</span>
		</td>
		<td style="padding-top:10px;">
			<div class="<?php echo $this->cycle(array('even', 'odd'));?>" style="padding:5px;border:1px solid #666">
				<div>
					<span class="smalltext">
						<strong>
							<?php echo $this->translate('Post');?>:
							<a href="<?php echo $this->url(array('tid' => $post['tid']),'forum_thread_show');?>/#pid<?php echo $post['pid'];?>" title="<?php echo $this->translate(sprintf('Post %s', $i));?>">#<?php echo $i;?></a>
						</strong>
					</span>
					<div class="clearer"></div>
				</div>
				<span class="smalltext"><strong><?php echo $this->escape($post['subject']);?></strong></span>
			</div>
			<br>
			<div><?php echo $this->escape($post['message']);?></div>
			<div>
				<div>
					<?php
						echo $this->translate(sprintf('This post was last modified: %s by %s.', '11-23-2010 10:26 AM', 'Nuxwin'));
					?>
				</div>
			</div>
		</td>
	</tr>
	<tr class="<?php echo $this->cycle(array('odd', 'even'));?>">
		<td>
			<span class="smalltext">02-15-2011 06:02 PM</span>
		</td>
		<td>
			<a href="#" title="<?php echo $this->translate('Edit this post');?>"><?php echo $this->translate('Edit');?></a>
			-
			<a href="<?php echo $this->url(array('tid' => $this->thread['tid'], 'pid' => $post['pid']), 'forum_post_delete');?>" title="<?php echo $this->translate('Delete this post');?>"><?php echo $this->translate('Delete');?></a>
			-
			<a href="<?php echo $this->url(array('tid' => 1, 'pid' => 2), 'forum_post_reply');?>" title="Quote this message in a reply"><?php echo $this->translate('Reply');?></a>
		</td>
	</tr>
	<?php $i++; endforeach;?>
	<tr>
		<td colspan="2">&nbsp;</td>
	</tr>
</table>

<p style="text-align:right">
	<a href="<?php echo $this->url(array('tid' => 1), 'forum_post_reply');?>" title="New Reply"><strong><?php echo $this->translate('New reply');?></strong></a>
</p>
