<h1 style="text-transform:none;font-size:1.5em;margin-top:20px;">
	<?php echo $this->translate('Forums');?>
</h1>

<?php if(count($this->forums)):?>
<table>
	<tr>
		<th colspan="5" style="text-align:left;background-color:#3B5998;color:#ffffff;">
				<strong><?php echo $this->translate('Forums Index');?></strong>
		</th>
	</tr>
	<tr>
		<th colspan="2" style="width:55%;text-align:left;"><?php echo $this->translate('Forum');?></th>
		<th style="width:10%;"><?php echo $this->translate('Threads');?></th>
		<th style="width:10%;"><?php echo $this->translate('Posts');?></th>
		<th style="width:25%;"><?php echo $this->translate('Last Post');?></th>
	</tr>
	<?php foreach($this->forums as $forum):?>
	<tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","#CCC"))->next();?>">
		<td style="width:7%;text-align:center;">
			<img src="/themes/default/images/imscp32x32.png" style="vertical-align:middle;" alt="status" />
		</td>
		<td>
			<a href="<?php echo $this->url(array('fid' => $forum['fid']), 'forum_show');?>"
			   title="View forum"><strong><?php echo $forum['name'];?></strong></a>
			<div style="font-size:0.8em;margin-top:5px;"><?php echo $forum['description'];?></div>
		</td>
		<td style="text-align:center"><?php echo $forum['count_threads'];?></td>
		<td style="text-align:center"><?php echo $forum['count_posts'];?></td>
		<td style="text-align:right;">
			<?php if($forum['count_posts'] > 0):?>
			<div style="font-size:0.8em;">
				<a href="<?php echo $this->url(array('tid' => $forum['lastthread_id'], 'action' => 'lastpost'), 'forum_thread_show');?>"
				   title="<?php echo $forum['lastthread_subject'];?>">
					<strong><?php echo $this->truncate($forum['lastthread_subject'], 25);?></strong>
				</a>
				<div class="meta">
					<?php echo date('d-m-Y g:i A', $forum['lastpost_date']);?>
					<br />
					<?php echo sprintf('by %s', $forum['lastposter_username']);?>
				</div>
			</div>
			<?php else:?>
			<div style="text-align:center"><?php echo $this->translate('Never');?></div>
			<?php endif;?>
		</td>
	</tr>
	<?php endforeach;?>
	<tr>
		<td colspan="5" style="text-align:left;background-color:#3B5998;color:#ffffff;">&nbsp;</td>
	</tr>
</table>
<?php else:?>
<div class="note"><?php echo $this->translate('No forums found!');?></div>
<?php endif;?>
