<?php if($this->comments()->hasComments()):?>
<div id="comments">
	<h3 class="commentsTitle"><?php echo $this->translate('%d answers to:');?> <?php echo $this->parent->getTitle();?></h3>
	<?php foreach($this->comments() as $comment):?>
	<ol class="commentList">
		<li class="comment <?php echo $this->cycle(array('even','odd'))->next();?>" id="liComment-<?php echo $comment;?>">
			<div id="comment-<?php echo $comment;?>">
				<div class="commentAuthor vcard">
					<img alt="" src="<?php echo $comment->getAvatar();?>" class='avatar avatar-40 photo avatar-default' height='40' width='40' />
					<cite class="fn">
						<?php echo $comment->getAuthorLink();?>
					</cite> <span class="says"><?php echo $this->translate('says');?>&nbsp;:</span>
				</div>
				<?php if(!$comment->isApproved()):?>
				<em class="commentAwaitingModeration"><?php echo $this->translate('your comment is awaiting moderation');?></em>
				<br>
				<?php endif;?>
				<div class="commentMeta commentMetadata"><?php echo $comment->getDate();?></div>
				<div class="commentBody">
					<p><?php echo $this->escape($comment->getText());?></p>
				</div>
			</div>
		</li>
	</ol>
	<?php endforeach;?>
</div>
<?php endif;?>
