<?php $this->headTitle('Authentication');?>
<h2>Authentication</h2>
<?php echo $this->form;?>

<?php if(isset($this->errorMessage)):?>
<div class="error"><?php echo $this->errorMessage;?></div>
<?php endif;?>

<p class="backLink">
    <a href="<?php echo $this->previousPage;?>" title="<?php echo $this->translate('Back to the previous page');?>">
        <span><strong><?php echo $this->translate('Back');?></strong></span>
    </a>
</p>