<?php $this->headTitle($this->translate('General Settings'));?>

<div id="ipmsbody-content">

    <!--
    <div id="screen-meta">
        <div id="contextual-help-wrap" class="hidden">
            <div class="metabox-prefs">
                <p>Les champs de cet écran déterminent certains des réglages de basede votre site.</p>
                <p>
                    La plupart des thèmes affichent le titre du site en haut de chaque page, dans la barre de titre du
                    navigateur, et en tant qu&rsquo;identifiant pour les flux de syndication, sauf si votre thème en
                    décide autrement. Le slogan est également utilisé par de nombreux thèmes.
                </p>
                <p>
                    L&rsquo;adresse web de WordPress et celle du site peuvent être identiques (<code>exemple.fr</code>)
                    ou différentes. Ainsi, vous pourriez avoir les fichiers de WordPress dans un sous-dossier
                    (<code>exemple.fr/wordpress</code>) plutôt qu&rsquo;à la racine du site.
                </p>
                <p>
                    Si vous voulez que les visiteurs du site puissent s&rsquo;inscrire eux-mêmes plutôt que de devoir
                    être inscrits par l&rsquo;administrateur du site, cochez la case &laquo;&nbsp;Inscription&nbsp;&raquo;.
                    Un rôle d&rsquo;utilisateur par défaut peut être assigné pour tout nouvel inscrit, qu&rsquo;il
                    se soit enregistré lui-même ou par le biais de l&rsquo;administrateur.
                </p>
                <p>UTC signifie Temps Universel Coordonné.</p>
                <p>
                    Veillez bien à cliquer sur le bouton &laquo;&nbsp;Enregistrer les modifications&nbsp;&raquo; en bas
                    de l&rsquo;écran pour que vos nouveaux réglages prennent effet.
                </p>
                <p><strong>Plus d&rsquo;informations&nbsp;:</strong></p>
                <p>
                    <a href="http://codex.wordpress.org/Settings_General_SubPanel" target="_blank">Documentation sur les
                        réglages généraux (en)</a>
                </p>
                <p><a href="http://www.wordpress-fr.net/support/" target="_blank">Forums&rsquo;entraide</a></p>
            </div>
        </div>
        <div id="screen-meta-links">
            <div id="contextual-help-link-wrap" class="hide-if-no-js screen-meta-toggle">
                <a href="#contextual-help" id="contextual-help-link" class="show-settings">Help</a>
            </div>
        </div>
    </div>
    -->
    <div class="wrap">
        <div id="icon-options-general" class="icon32"><br /></div>
        <h2>Options générales</h2>
        <form method="post" action="options.php">
            <input type='hidden' name='option_page' value='general' />
            <input type="hidden" name="action" value="update" />
            <input type="hidden" id="_ipmsnonce" name="_ipmsnonce" value="94710be035" />
            <input type="hidden" name="_ipms_http_referer" value="/ipms-admin/options-general.php" />
            <table class="form-table">
                <tr valign="top">
                    <th scope="row">
                        <label for="blogname">Titre du site</label>
                    </th>
                    <td>
                        <input name="blogname" type="text" id="blogname" value="i-PMS - internet Multi Server Control Panel" class="regular-text" />
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">
                        <label for="blogdescription">Slogan</label>
                    </th>
                    <td>
                        <input name="blogdescription" type="text" id="blogdescription" value="Un site utilisant i-PMS" class="regular-text" />
                        <span class="description">En quelques mots, décrivez la raison d&rsquo;être de ce site.</span>
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">
                        <label for="siteurl">Adresse web de WordPress</label>
                    </th>
                    <td>
                        <input name="siteurl" type="text" id="siteurl" value="http://wordpress.i-mscp.net" class="regular-text code" />
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">
                        <label for="home">Adresse web du site (URL)</label>
                    </th>
                    <td>
                        <input name="home" type="text" id="home" value="http://wordpress.i-mscp.net" class="regular-text code" />
                        <span class="description">
                             Si vous souhaitez que l&rsquo;adresse de la page d&rsquo;accueil de votre site <a
                             href="http://codex.wordpress.org/Giving_WordPress_Its_Own_Directory">soit différente du
                             répertoire (en)</a> où vous avez installé WordPress, saisissez cette adresse ici.
                        </span>
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">
                        <label for="admin_email">Adresse de messagerie</label>
                    </th>
                    <td>
                        <input name="admin_email" type="text" id="admin_email" value="l.declercq@nuxwin.com" class="regular-text" />
                        <span class="description">Cette adresse n&rsquo;est utilisée que pour l&rsquo;administration du site&nbsp;; par exemple, la notification de l&rsquo;inscription d&rsquo;un nouvel utilisateur.</span>
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row">Inscription</th>
                    <td>
                        <fieldset>
                            <legend class="screen-reader-text"><span>Inscription</span></legend>
                            <label for="users_can_register">
                                <input name="users_can_register" type="checkbox" id="users_can_register" value="1" checked='checked' />
                                Tout le monde peut s&rsquo;enregistrer
                            </label>
                        </fieldset>
                    </td>
                </tr>
                <tr valign="top">
                    <th scope="row"><label for="default_role">Rôle par défaut de tout nouvel utilisateur</label></th>
                    <td>
                        <select name="default_role" id="default_role">
                            <option selected='selected' value='subscriber'>Abonné</option>
                            <option value='administrator'>Administrateur</option>
                            <option value='editor'>Éditeur</option>
                            <option value='author'>Auteur</option>
                            <option value='contributor'>Contributeur</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="timezone_string">Fuseau horaire</label></th>
                    <td>
                        <select id="timezone_string" name="timezone_string">
                            <optgroup label="Afrique">
                                <option value="Africa/Abidjan">Abidjan</option>
                                <option value="Africa/Accra">Accra</option>
                                <option value="Africa/Addis_Ababa">Addis-Abeba</option>
                                <option value="Africa/Algiers">Alger</option>
                                <option value="Africa/Asmara">Asmara</option>
                                <option value="Africa/Bamako">Bamako</option>
                                <option value="Africa/Bangui">Bangui</option>
                                <option value="Africa/Banjul">Banjul</option>
                                <option value="Africa/Bissau">Bissau</option>
                                <option value="Africa/Blantyre">Blantyre</option>
                                <option value="Africa/Brazzaville">Brazzaville</option>
                                <option value="Africa/Bujumbura">Bujumbura</option>
                                <option value="Africa/Casablanca">Casablanca</option>
                                <option value="Africa/Ceuta">Ceuta</option>
                                <option value="Africa/Conakry">Conakry</option>
                                <option value="Africa/Dakar">Dakar</option>
                                <option value="Africa/Dar_es_Salaam">Dar es Salaam</option>
                                <option value="Africa/Djibouti">Djibouti</option>
                                <option value="Africa/Douala">Douala</option>
                                <option value="Africa/Freetown">Freetown</option>
                                <option value="Africa/Gaborone">Gaborone</option>
                                <option value="Africa/Harare">Harare</option>
                                <option value="Africa/Johannesburg">Johannesburg</option>
                                <option value="Africa/Kampala">Kampala</option>
                                <option value="Africa/Khartoum">Khartoum</option>
                                <option value="Africa/Kigali">Kigali</option>
                                <option value="Africa/Kinshasa">Kinshasa</option>
                                <option value="Africa/Lagos">Lagos</option>
                                <option value="Africa/El_Aaiun">Laâyoune</option>
                                <option value="Africa/Cairo">Le Caire</option>
                                <option value="Africa/Libreville">Libreville</option>
                                <option value="Africa/Lome">Lomé</option>
                                <option value="Africa/Luanda">Luanda</option>
                                <option value="Africa/Lubumbashi">Lubumbashi</option>
                                <option value="Africa/Lusaka">Lusaka</option>
                                <option value="Africa/Malabo">Malabo</option>
                                <option value="Africa/Maputo">Maputo</option>
                                <option value="Africa/Maseru">Maseru</option>
                                <option value="Africa/Mbabane">Mbabane</option>
                                <option value="Africa/Mogadishu">Mogadiscio</option>
                                <option value="Africa/Monrovia">Monrovia</option>
                                <option value="Africa/Ndjamena">N&#039;Djamena</option>
                                <option value="Africa/Nairobi">Nairobi</option>
                                <option value="Africa/Niamey">Niamey</option>
                                <option value="Africa/Nouakchott">Nouakchott</option>
                                <option value="Africa/Ouagadougou">Ouagadougou</option>
                                <option value="Africa/Porto-Novo">Porto-Novo</option>
                                <option value="Africa/Sao_Tome">São Tomé</option>
                                <option value="Africa/Tripoli">Tripoli</option>
                                <option value="Africa/Tunis">Tunis</option>
                                <option value="Africa/Windhoek">Windhoek</option>
                            </optgroup>
                            <optgroup label="Amériques">
                                <option value="America/Adak">Adak</option>
                                <option value="America/Anchorage">Anchorage</option>
                                <option value="America/Anguilla">Anguilla</option>
                                <option value="America/Antigua">Antigua</option>
                                <option value="America/Araguaina">Araguaína</option>
                                <option value="America/Argentina/Buenos_Aires">Argentine - Buenos Aires</option>
                                <option value="America/Argentina/Catamarca">Argentine - Catamarca</option>
                                <option value="America/Argentina/Cordoba">Argentine - Córdoba</option>
                                <option value="America/Argentina/La_Rioja">Argentine - La Rioja</option>
                                <option value="America/Argentina/Mendoza">Argentine - Mendoza</option>
                                <option value="America/Argentina/Rio_Gallegos">Argentine - Rio Gallegos</option>
                                <option value="America/Argentina/Salta">Argentine - Salta</option>
                                <option value="America/Argentina/San_Juan">Argentine - San Juan</option>
                                <option value="America/Argentina/San_Luis">Argentine - San Luis</option>
                                <option value="America/Argentina/Tucuman">Argentine - San Miguel de Tucumán</option>
                                <option value="America/Argentina/Jujuy">Argentine - San Salvador de Jujuy</option>
                                <option value="America/Argentina/Ushuaia">Argentine - Ushuaïa</option>
                                <option value="America/Aruba">Aruba</option>
                                <option value="America/Asuncion">Asunción</option>
                                <option value="America/Atikokan">Atikokan</option>
                                <option value="America/Bahia">Bahia</option>
                                <option value="America/Bahia_Banderas">Bahia Banderas</option>
                                <option value="America/Barbados">Barbade</option>
                                <option value="America/Belize">Belize</option>
                                <option value="America/Belem">Belém</option>
                                <option value="America/Blanc-Sablon">Blanc-Sablon</option>
                                <option value="America/Boa_Vista">Boa Vista</option>
                                <option value="America/Bogota">Bogotá</option>
                                <option value="America/Boise">Boise</option>
                                <option value="America/Campo_Grande">Campo Grande</option>
                                <option value="America/Cancun">Cancún</option>
                                <option value="America/Caracas">Caracas</option>
                                <option value="America/Cayenne">Cayenne</option>
                                <option value="America/Chicago">Chicago</option>
                                <option value="America/Costa_Rica">Costa Rica</option>
                                <option value="America/Cuiaba">Cuiabá</option>
                                <option value="America/Curacao">Curaçao</option>
                                <option value="America/North_Dakota/Beulah">Dakota du Nord - Beulah</option>
                                <option value="America/North_Dakota/Center">Dakota du Nord - Center</option>
                                <option value="America/North_Dakota/New_Salem">Dakota du Nord - New Salem</option>
                                <option value="America/Danmarkshavn">Danmarkshavn</option>
                                <option value="America/Dawson">Dawson</option>
                                <option value="America/Dawson_Creek">Dawson Creek</option>
                                <option value="America/Denver">Denver</option>
                                <option value="America/Detroit">Detroit</option>
                                <option value="America/Dominica">Dominique</option>
                                <option value="America/Edmonton">Edmonton</option>
                                <option value="America/Eirunepe">Eirunepé</option>
                                <option value="America/Chihuahua">Etat de Chihuahua</option>
                                <option value="America/Fortaleza">Fortaleza</option>
                                <option value="America/Glace_Bay">Glace Bay</option>
                                <option value="America/Goose_Bay">Goose Bay</option>
                                <option value="America/Grand_Turk">Grand Turk</option>
                                <option value="America/Grenada">Grenade</option>
                                <option value="America/Guadeloupe">Guadeloupe</option>
                                <option value="America/Guatemala">Guatemala</option>
                                <option value="America/Guayaquil">Guayaquil</option>
                                <option value="America/Guyana">Guyane</option>
                                <option value="America/Halifax">Halifax</option>
                                <option value="America/Hermosillo">Hermosillo</option>
                                <option value="America/Cambridge_Bay">Ikaluktutiak</option>
                                <option value="America/Indiana/Indianapolis">Indiana - Indianapolis</option>
                                <option value="America/Indiana/Knox">Indiana - Knox</option>
                                <option value="America/Indiana/Marengo">Indiana - Marengo</option>
                                <option value="America/Indiana/Petersburg">Indiana - Petersburg</option>
                                <option value="America/Indiana/Tell_City">Indiana - Tell City</option>
                                <option value="America/Indiana/Vevay">Indiana - Vevay</option>
                                <option value="America/Indiana/Vincennes">Indiana - Vincennes</option>
                                <option value="America/Indiana/Winamac">Indiana - Winamac</option>
                                <option value="America/Inuvik">Inuvik</option>
                                <option value="America/Iqaluit">Iqaluit</option>
                                <option value="America/Scoresbysund">Ittoqqortoormiit (Scoresbysund)</option>
                                <option value="America/Jamaica">Jamaïque</option>
                                <option value="America/Juneau">Juneau</option>
                                <option value="America/Rankin_Inlet">Kangiqtiniq (Rankin Inlet)</option>
                                <option value="America/Kentucky/Louisville">Kentucky - Louisville</option>
                                <option value="America/Kentucky/Monticello">Kentucky - Monticello</option>
                                <option value="America/Havana">La Havane</option>
                                <option value="America/La_Paz">La Paz</option>
                                <option value="America/Lima">Lima</option>
                                <option value="America/Los_Angeles">Los Angeles</option>
                                <option value="America/Maceio">Maceió</option>
                                <option value="America/Managua">Managua</option>
                                <option value="America/Manaus">Manaus</option>
                                <option value="America/Marigot">Marigot</option>
                                <option value="America/Martinique">Martinique</option>
                                <option value="America/Matamoros">Matamoros</option>
                                <option value="America/Mazatlan">Mazatlan</option>
                                <option value="America/Menominee">Menominee</option>
                                <option value="America/Merida">Merida</option>
                                <option value="America/Metlakatla">Metlakatla</option>
                                <option value="America/Mexico_City">Mexico</option>
                                <option value="America/Miquelon">Miquelon</option>
                                <option value="America/Moncton">Moncton</option>
                                <option value="America/Monterrey">Monterrey</option>
                                <option value="America/Montevideo">Montevideo</option>
                                <option value="America/Montreal">Montréal</option>
                                <option value="America/Montserrat">Montserrat</option>
                                <option value="America/Nassau">Nassau</option>
                                <option value="America/New_York">New York</option>
                                <option value="America/Nipigon">Nipigon</option>
                                <option value="America/Nome">Nome</option>
                                <option value="America/Noronha">Noronha</option>
                                <option value="America/Godthab">Nuuk (Godthåb)</option>
                                <option value="America/Ojinaga">Ojinaga</option>
                                <option value="America/Panama">Panama</option>
                                <option value="America/Pangnirtung">Pangnirtung</option>
                                <option value="America/Paramaribo">Paramaribo</option>
                                <option value="America/Phoenix">Phoenix</option>
                                <option value="America/Port-au-Prince">Port-au-Prince</option>
                                <option value="America/Port_of_Spain">Port-d&#039;Espagne</option>
                                <option value="America/Puerto_Rico">Porto Rico</option>
                                <option value="America/Porto_Velho">Porto Velho</option>
                                <option value="America/Rainy_River">Rainy River</option>
                                <option value="America/Recife">Recife</option>
                                <option value="America/Regina">Regina</option>
                                <option value="America/Resolute">Resolute</option>
                                <option value="America/Rio_Branco">Rio Branco</option>
                                <option value="America/St_Barthelemy">Saint-Barthélemy</option>
                                <option value="America/Santo_Domingo">Saint-Domingue</option>
                                <option value="America/St_Lucia">Sainte-Lucie</option>
                                <option value="America/St_Johns">Saint John&#039;s</option>
                                <option value="America/St_Thomas">Saint Thomas</option>
                                <option value="America/St_Vincent">Saint Vincent</option>
                                <option value="America/El_Salvador">Salvador</option>
                                <option value="America/Santa_Isabel">Santa Isabel</option>
                                <option value="America/Santarem">Santarem</option>
                                <option value="America/Santiago">Santiago du Chili</option>
                                <option value="America/Shiprock">Shiprock</option>
                                <option value="America/Sitka">Sitka</option>
                                <option value="America/Swift_Current">Swift Current</option>
                                <option value="America/Sao_Paulo">São Paulo</option>
                                <option value="America/Tegucigalpa">Tegucigalpa</option>
                                <option value="America/Thule">Thule</option>
                                <option value="America/Thunder_Bay">Thunder Bay</option>
                                <option value="America/Tijuana">Tijuana</option>
                                <option value="America/Toronto">Toronto</option>
                                <option value="America/Tortola">Tortola</option>
                                <option value="America/Vancouver">Vancouver</option>
                                <option value="America/Whitehorse">Whitehorse</option>
                                <option value="America/Winnipeg">Winnipeg</option>
                                <option value="America/Yakutat">Yakutat</option>
                                <option value="America/Yellowknife">Yellowknife</option>
                                <option value="America/St_Kitts">Île Saint-Christophe</option>
                                <option value="America/Cayman">Îles Caïmans</option>
                            </optgroup>
                            <optgroup label="Antartique">
                                <option value="Antarctica/Casey">Casey</option>
                                <option value="Antarctica/Davis">Davis</option>
                                <option value="Antarctica/DumontDUrville">Dumont d&#039;Urville</option>
                                <option value="Antarctica/Macquarie">Macquarie</option>
                                <option value="Antarctica/Mawson">Mawson</option>
                                <option value="Antarctica/McMurdo">McMurdo</option>
                                <option value="Antarctica/Palmer">Palmer</option>
                                <option value="Antarctica/South_Pole">Pôle Sud</option>
                                <option value="Antarctica/Rothera">Rothera</option>
                                <option value="Antarctica/Syowa">Syowa</option>
                                <option value="Antarctica/Vostok">Vostok</option>
                            </optgroup>
                            <optgroup label="Arctique">
                                <option value="Arctic/Longyearbyen">Longyearbyen</option>
                            </optgroup>
                            <optgroup label="Asie">
                                <option value="Asia/Ashgabat">Achgabat</option>
                                <option value="Asia/Aden">Aden</option>
                                <option value="Asia/Aqtobe">Aktioubé</option>
                                <option value="Asia/Almaty">Almaty</option>
                                <option value="Asia/Amman">Amman</option>
                                <option value="Asia/Anadyr">Anadyr</option>
                                <option value="Asia/Aqtau">Aqtou</option>
                                <option value="Asia/Baghdad">Bagdad</option>
                                <option value="Asia/Bahrain">Bahreïn</option>
                                <option value="Asia/Baku">Bakou</option>
                                <option value="Asia/Bangkok">Bangkok</option>
                                <option value="Asia/Beirut">Beyrouth</option>
                                <option value="Asia/Bishkek">Bichkek</option>
                                <option value="Asia/Brunei">Brunei</option>
                                <option value="Asia/Kolkata">Calcutta</option>
                                <option value="Asia/Chongqing">Chongqing</option>
                                <option value="Asia/Choibalsan">Choybalsan</option>
                                <option value="Asia/Colombo">Colombo</option>
                                <option value="Asia/Damascus">Damas</option>
                                <option value="Asia/Dhaka">Dhâkâ (Dacca)</option>
                                <option value="Asia/Dili">Dili</option>
                                <option value="Asia/Dushanbe">Douchanbé</option>
                                <option value="Asia/Dubai">Dubaï</option>
                                <option value="Asia/Gaza">Gaza</option>
                                <option value="Asia/Harbin">Harbin</option>
                                <option value="Asia/Hong_Kong">Hong Kong</option>
                                <option value="Asia/Hovd">Hovd</option>
                                <option value="Asia/Ho_Chi_Minh">Hô-Chi-Minh-Ville</option>
                                <option value="Asia/Yakutsk">Iakoutsk</option>
                                <option value="Asia/Yekaterinburg">Iekaterinbourg</option>
                                <option value="Asia/Irkutsk">Irkoutsk</option>
                                <option value="Asia/Jakarta">Jakarta</option>
                                <option value="Asia/Jayapura">Jayapura</option>
                                <option value="Asia/Jerusalem">Jérusalem</option>
                                <option value="Asia/Kabul">Kaboul</option>
                                <option value="Asia/Kashgar">Kachgar</option>
                                <option value="Asia/Kamchatka">Kamtchatka</option>
                                <option value="Asia/Karachi">Karachi</option>
                                <option value="Asia/Kathmandu">Kathmandu</option>
                                <option value="Asia/Kuwait">Koweït</option>
                                <option value="Asia/Krasnoyarsk">Krasnoïarsk</option>
                                <option value="Asia/Kuala_Lumpur">Kuala Lumpur</option>
                                <option value="Asia/Kuching">Kuching</option>
                                <option value="Asia/Qyzylorda">Kyzylorda</option>
                                <option value="Asia/Macau">Macao</option>
                                <option value="Asia/Magadan">Magadan</option>
                                <option value="Asia/Makassar">Makassar</option>
                                <option value="Asia/Manila">Manille</option>
                                <option value="Asia/Muscat">Mascate</option>
                                <option value="Asia/Nicosia">Nicosie</option>
                                <option value="Asia/Novokuznetsk">Novokuznetsk</option>
                                <option value="Asia/Novosibirsk">Novossibirsk</option>
                                <option value="Asia/Omsk">Omsk</option>
                                <option value="Asia/Ulaanbaatar">Oulan-Bator (Ulaanbaatar)</option>
                                <option value="Asia/Oral">Oural</option>
                                <option value="Asia/Phnom_Penh">Phnom Penh</option>
                                <option value="Asia/Pontianak">Pontianak</option>
                                <option value="Asia/Pyongyang">Pyongyang</option>
                                <option value="Asia/Qatar">Qatar</option>
                                <option value="Asia/Rangoon">Rangoon</option>
                                <option value="Asia/Riyadh">Riyad</option>
                                <option value="Asia/Sakhalin">Sakhaline</option>
                                <option value="Asia/Samarkand">Samarcande</option>
                                <option value="Asia/Shanghai">Shanghai</option>
                                <option value="Asia/Singapore">Singapour</option>
                                <option value="Asia/Seoul">Séoul</option>
                                <option value="Asia/Tashkent">Tachkent</option>
                                <option value="Asia/Taipei">Taipei</option>
                                <option value="Asia/Tbilisi">Tbilissi</option>
                                <option value="Asia/Thimphu">Thimphou</option>
                                <option value="Asia/Tehran">Téhéran</option>
                                <option value="Asia/Tokyo">Tōkyō</option>
                                <option value="Asia/Vientiane">Vientiane</option>
                                <option value="Asia/Vladivostok">Vladivostok</option>
                                <option value="Asia/Yerevan">Yerevan (Erevan)</option>
                                <option value="Asia/Urumqi">Ürümqi</option>
                            </optgroup>
                            <optgroup label="Atlantique">
                                <option value="Atlantic/Azores">Açores</option>
                                <option value="Atlantic/Bermuda">Bermudes</option>
                                <option value="Atlantic/Cape_Verde">Cap-Vert</option>
                                <option value="Atlantic/Madeira">Madère</option>
                                <option value="Atlantic/Reykjavik">Reykjavík</option>
                                <option value="Atlantic/St_Helena">Sainte-Hélène</option>
                                <option value="Atlantic/Stanley">Stanley</option>
                                <option value="Atlantic/South_Georgia">Île de Géorgie du Sud</option>
                                <option value="Atlantic/Canary">Îles Canaries</option>
                                <option value="Atlantic/Faroe">Îles Féroé</option>
                            </optgroup>
                            <optgroup label="Australie">
                                <option value="Australia/Adelaide">Adélaïde</option>
                                <option value="Australia/Brisbane">Brisbane</option>
                                <option value="Australia/Broken_Hill">Broken Hill</option>
                                <option value="Australia/Currie">Currie</option>
                                <option value="Australia/Darwin">Darwin</option>
                                <option value="Australia/Eucla">Eucla</option>
                                <option value="Australia/Hobart">Hobart</option>
                                <option value="Australia/Lindeman">Lindeman</option>
                                <option value="Australia/Melbourne">Melbourne</option>
                                <option value="Australia/Perth">Perth</option>
                                <option value="Australia/Sydney">Sydney</option>
                                <option value="Australia/Lord_Howe">Île Lord Howe (LHI)</option>
                            </optgroup>
                            <optgroup label="Europe">
                                <option value="Europe/Amsterdam">Amsterdam</option>
                                <option value="Europe/Andorra">Andorre</option>
                                <option value="Europe/Athens">Athènes</option>
                                <option value="Europe/Belgrade">Belgrade</option>
                                <option value="Europe/Berlin">Berlin</option>
                                <option value="Europe/Bratislava">Bratislava</option>
                                <option value="Europe/Brussels">Bruxelles</option>
                                <option value="Europe/Bucharest">Bucarest</option>
                                <option value="Europe/Budapest">Budapest</option>
                                <option value="Europe/Chisinau">Chişinău (Kichinev)</option>
                                <option value="Europe/Copenhagen">Copenhague</option>
                                <option value="Europe/Dublin">Dublin</option>
                                <option value="Europe/Gibraltar">Gibraltar</option>
                                <option value="Europe/Guernsey">Guernsey</option>
                                <option value="Europe/Helsinki">Helsinki</option>
                                <option value="Europe/Istanbul">Istanbul</option>
                                <option value="Europe/Jersey">Jersey</option>
                                <option value="Europe/Kaliningrad">Kaliningrad</option>
                                <option value="Europe/Kiev">Kiev</option>
                                <option value="Europe/Lisbon">Lisbonne</option>
                                <option value="Europe/Ljubljana">Ljubljana</option>
                                <option value="Europe/London">Londres</option>
                                <option value="Europe/Luxembourg">Luxembourg</option>
                                <option value="Europe/Madrid">Madrid</option>
                                <option value="Europe/Malta">Malte</option>
                                <option value="Europe/Mariehamn">Mariehamn</option>
                                <option value="Europe/Minsk">Minsk</option>
                                <option value="Europe/Monaco">Monaco</option>
                                <option value="Europe/Moscow">Moscou</option>
                                <option value="Europe/Oslo">Oslo</option>
                                <option value="Europe/Uzhgorod">Oujhorod (Uzhgorod)</option>
                                <option selected="selected" value="Europe/Paris">Paris</option>
                                <option value="Europe/Podgorica">Podgorica</option>
                                <option value="Europe/Prague">Prague</option>
                                <option value="Europe/Riga">Riga</option>
                                <option value="Europe/Rome">Rome</option>
                                <option value="Europe/San_Marino">Saint-Marin</option>
                                <option value="Europe/Samara">Samara</option>
                                <option value="Europe/Sarajevo">Sarajevo</option>
                                <option value="Europe/Simferopol">Simferopol</option>
                                <option value="Europe/Skopje">Skopje</option>
                                <option value="Europe/Sofia">Sofia</option>
                                <option value="Europe/Stockholm">Stockholm</option>
                                <option value="Europe/Tallinn">Tallinn</option>
                                <option value="Europe/Tirane">Tirana</option>
                                <option value="Europe/Vaduz">Vaduz</option>
                                <option value="Europe/Warsaw">Varsovie</option>
                                <option value="Europe/Vatican">Vatican</option>
                                <option value="Europe/Vienna">Vienne</option>
                                <option value="Europe/Vilnius">Vilnius</option>
                                <option value="Europe/Volgograd">Volgograd</option>
                                <option value="Europe/Zagreb">Zagreb</option>
                                <option value="Europe/Zaporozhye">Zaporojie</option>
                                <option value="Europe/Zurich">Zurich</option>
                                <option value="Europe/Isle_of_Man">Île de Man</option>
                            </optgroup>
                            <optgroup label="Océan Indien">
                                <option value="Indian/Antananarivo">Antananarivo</option>
                                <option value="Indian/Chagos">Archipel des Chagos</option>
                                <option value="Indian/Comoro">Archipel des Comores</option>
                                <option value="Indian/Mahe">Mahé</option>
                                <option value="Indian/Maldives">Maldives</option>
                                <option value="Indian/Mayotte">Mayotte</option>
                                <option value="Indian/Christmas">Île Christmas</option>
                                <option value="Indian/Reunion">Île de la Réunion</option>
                                <option value="Indian/Mauritius">Île Maurice</option>
                                <option value="Indian/Cocos">Îles Cocos</option>
                                <option value="Indian/Kerguelen">Îles Kerguelen</option>
                            </optgroup>
                            <optgroup label="Océan Pacifique">
                                <option value="Pacific/Apia">Apia</option>
                                <option value="Pacific/Johnston">Atoll de Johnston</option>
                                <option value="Pacific/Midway">Atoll de Midway</option>
                                <option value="Pacific/Auckland">Auckland</option>
                                <option value="Pacific/Chuuk">Chuuk</option>
                                <option value="Pacific/Enderbury">Enderbury</option>
                                <option value="Pacific/Fakaofo">Fakaofo</option>
                                <option value="Pacific/Fiji">Fidji</option>
                                <option value="Pacific/Funafuti">Funafuti</option>
                                <option value="Pacific/Guadalcanal">Guadalcanal</option>
                                <option value="Pacific/Guam">Guam</option>
                                <option value="Pacific/Honolulu">Honolulu</option>
                                <option value="Pacific/Kosrae">Kosrae</option>
                                <option value="Pacific/Kwajalein">Kwajalein</option>
                                <option value="Pacific/Majuro">Majuro</option>
                                <option value="Pacific/Nauru">Nauru</option>
                                <option value="Pacific/Niue">Niué</option>
                                <option value="Pacific/Norfolk">Norfolk</option>
                                <option value="Pacific/Noumea">Nouméa</option>
                                <option value="Pacific/Pago_Pago">Pago Pago</option>
                                <option value="Pacific/Palau">Palaos</option>
                                <option value="Pacific/Pohnpei">Pohnpei</option>
                                <option value="Pacific/Port_Moresby">Port Moresby</option>
                                <option value="Pacific/Rarotonga">Rarotonga</option>
                                <option value="Pacific/Saipan">Saipan</option>
                                <option value="Pacific/Tahiti">Tahiti</option>
                                <option value="Pacific/Tarawa">Tarawa</option>
                                <option value="Pacific/Tongatapu">Tongatapu</option>
                                <option value="Pacific/Wallis">Wallis-et-Futuna</option>
                                <option value="Pacific/Efate">Éfaté</option>
                                <option value="Pacific/Kiritimati">Île Christmas (Kiribati)</option>
                                <option value="Pacific/Easter">Île de Pâques</option>
                                <option value="Pacific/Chatham">Îles Chatham</option>
                                <option value="Pacific/Galapagos">Îles Galápagos</option>
                                <option value="Pacific/Gambier">Îles Gambier</option>
                                <option value="Pacific/Marquesas">Îles Marquises</option>
                                <option value="Pacific/Pitcairn">Îles Pitcairn</option>
                                <option value="Pacific/Wake">Île Wake</option>
                            </optgroup>
                            <optgroup label="UTC">
                                <option value="UTC">UTC</option>
                            </optgroup>
                            <optgroup label="Décalages manuels">
                                <option value="UTC-12">UTC-12</option>
                                <option value="UTC-11.5">UTC-11:30</option>
                                <option value="UTC-11">UTC-11</option>
                                <option value="UTC-10.5">UTC-10:30</option>
                                <option value="UTC-10">UTC-10</option>
                                <option value="UTC-9.5">UTC-9:30</option>
                                <option value="UTC-9">UTC-9</option>
                                <option value="UTC-8.5">UTC-8:30</option>
                                <option value="UTC-8">UTC-8</option>
                                <option value="UTC-7.5">UTC-7:30</option>
                                <option value="UTC-7">UTC-7</option>
                                <option value="UTC-6.5">UTC-6:30</option>
                                <option value="UTC-6">UTC-6</option>
                                <option value="UTC-5.5">UTC-5:30</option>
                                <option value="UTC-5">UTC-5</option>
                                <option value="UTC-4.5">UTC-4:30</option>
                                <option value="UTC-4">UTC-4</option>
                                <option value="UTC-3.5">UTC-3:30</option>
                                <option value="UTC-3">UTC-3</option>
                                <option value="UTC-2.5">UTC-2:30</option>
                                <option value="UTC-2">UTC-2</option>
                                <option value="UTC-1.5">UTC-1:30</option>
                                <option value="UTC-1">UTC-1</option>
                                <option value="UTC-0.5">UTC-0:30</option>
                                <option value="UTC+0">UTC+0</option>
                                <option value="UTC+0.5">UTC+0:30</option>
                                <option value="UTC+1">UTC+1</option>
                                <option value="UTC+1.5">UTC+1:30</option>
                                <option value="UTC+2">UTC+2</option>
                                <option value="UTC+2.5">UTC+2:30</option>
                                <option value="UTC+3">UTC+3</option>
                                <option value="UTC+3.5">UTC+3:30</option>
                                <option value="UTC+4">UTC+4</option>
                                <option value="UTC+4.5">UTC+4:30</option>
                                <option value="UTC+5">UTC+5</option>
                                <option value="UTC+5.5">UTC+5:30</option>
                                <option value="UTC+5.75">UTC+5:45</option>
                                <option value="UTC+6">UTC+6</option>
                                <option value="UTC+6.5">UTC+6:30</option>
                                <option value="UTC+7">UTC+7</option>
                                <option value="UTC+7.5">UTC+7:30</option>
                                <option value="UTC+8">UTC+8</option>
                                <option value="UTC+8.5">UTC+8:30</option>
                                <option value="UTC+8.75">UTC+8:45</option>
                                <option value="UTC+9">UTC+9</option>
                                <option value="UTC+9.5">UTC+9:30</option>
                                <option value="UTC+10">UTC+10</option>
                                <option value="UTC+10.5">UTC+10:30</option>
                                <option value="UTC+11">UTC+11</option>
                                <option value="UTC+11.5">UTC+11:30</option>
                                <option value="UTC+12">UTC+12</option>
                                <option value="UTC+12.75">UTC+12:45</option>
                                <option value="UTC+13">UTC+13</option>
                                <option value="UTC+13.75">UTC+13:45</option>
                                <option value="UTC+14">UTC+14</option>
                            </optgroup>
                        </select>
        <span id="utc-time"> L&rsquo;heure <abbr title="Temps universel coordonné">UTC</abbr> actuelle est <code>2011-04-03
            9:26:49</code></span>
                        <span id="local-time">L&rsquo;heure locale actuelle est <code>2011-04-03 11:26:49</code></span>
                        <br />
                        <span class="description">Choisissez une ville dans le même fuseau horaire que le vôtre.</span>
                        <br />
            <span>
                Ce fuseau horaire est actuellement à l&rsquo;heure d&rsquo;été.	<br /> Le passage à l&rsquo;heure
                d&rsquo;hiver se fait le <code>30 octobre 2011 3 h 00 min</code>.
            </span>
                    </td>
                </tr>
                <tr>
                    <th scope="row">Format de date</th>
                    <td>
                        <fieldset>
                            <legend class="screen-reader-text"><span>Format de date</span></legend>
                            <label title='j F Y'>
                                <input type='radio' name='date_format' value='j F Y' checked='checked' />
                                <span>3 avril 2011</span>
                            </label>
                            <br />
                            <label title='Y/m/d'>
                                <input type='radio' name='date_format' value='Y/m/d' />
                                <span>2011/04/03</span>
                            </label>
                            <br />
                            <label title='m/d/Y'>
                                <input type='radio' name='date_format' value='m/d/Y' />
                                <span>04/03/2011</span>
                            </label><br />
                            <label title='d/m/Y'>
                                <input type='radio' name='date_format' value='d/m/Y' />
                                <span>03/04/2011</span>
                            </label><br />
                            <label>
                                <input type="radio" name="date_format" id="date_format_custom_radio" value="\c\u\s\t\o\m" />
                                Personnalisé&nbsp;:
                            </label>
                            <input type="text" name="date_format_custom" value="j F Y" class="small-text" />
                            <span class="example"> 3 avril 2011</span>
                            <img class='ajax-loading' src='http://wordpress.i-mscp.net/ipms-admin/images/ipmsspin_light.gif' />

                            <p>
                                <a href="http://codex.wordpress.org/Formatting_Date_and_Time">Documentation sur le
                                    formatdes
                                    dates (en)</a>.
                            </p>
                        </fieldset>
                    </td>
                </tr>
                <tr>
                    <th scope="row">Format d’heure</th>
                    <td>
                        <fieldset>
                            <legend class="screen-reader-text"><span>Format d’heure</span></legend>
                            <label title='G \h i \m\i\n'>
                                <input type='radio' name='time_format' value='G \h i \m\i\n' checked='checked' />
                                <span>11 h 26 min</span>
                            </label>
                            <br />
                            <label title='g:i A'>
                                <input type='radio' name='time_format' value='g:i A' />
                                <span>11:26  </span>
                            </label>
                            <br />
                            <label title='H:i'>
                                <input type='radio' name='time_format' value='H:i' />
                                <span>11:26</span>
                            </label>
                            <br />
                            <label>
                                <input type="radio" name="time_format" id="time_format_custom_radio" value="\c\u\s\t\o\m" />
                                Personnalisé&nbsp;:
                            </label>
                            <input type="text" name="time_format_custom" value="G \h i \m\i\n" class="small-text" />
                            <span class="example"> 11 h 26 min</span>
                            <img class='ajax-loading' src='http://wordpress.i-mscp.net/ipms-admin/images/ipmsspin_light.gif' />
                        </fieldset>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="start_of_week">La semaine débute&nbsp;le</label></th>
                    <td>
                        <select name="start_of_week" id="start_of_week">
                            <option value='0'>Dimanche</option>
                            <option value='1' selected="selected">Lundi</option>
                            <option value='2'>Mardi</option>
                            <option value='3'>Mercredi</option>
                            <option value='4'>Jeudi</option>
                            <option value='5'>Vendredi</option>
                            <option value='6'>Samedi</option>
                        </select>
                    </td>
                </tr>
            </table>
            <p class="submit">
                <input type="submit" name="submit" id="submit" class="button-primary" value="Enregistrer les modifications" />
            </p>
        </form>
    </div>
    <div class="clear"></div>
</div>

<!--
<h2 class="settingsMediumIcon mediumIcon" style="margin-top:10px;">General Settings</h2>
<br />
<div style="color:rgb(29, 42, 91);background:#f9f9f9;border:0px solid rgb(29, 42, 91);">
    <?php// echo $this->form;?>
    <div class="clearer"></div>
</div>
-->