<div id="paginationInner">
    <?php if (isset($this->previous)):?>
    <p id="paginationPrevious">
        <a href="<?php echo $this->url(array('page' => $this->previous), 'posts');?>" title="Previous page">
            <span><?php echo $this->translate('Previous page');?></span>
        </a>
    </p>
    <?php else:?>
    <p id="paginationPrevious">
        <?php echo $this->translate('Previous page');?>
    </p>
    <?php endif;?>
    <p id="paginationNumbered">
        <?php foreach ($this->pagesInRange as $page):
            if ($page != $this->current):?>
            <a href="<?php echo $this->url(array('page' => $page), 'posts');?>"><span><?php echo $page;?></span></a>
            <?php else:
                echo $page;
            endif;
        endforeach;?>
    </p>
    <?php if (isset($this->next)):?>
    <p id="paginationNext">
        <a href="<?php echo $this->url(array('page' => $this->next));?>" title="Next page">
            <span><?php echo $this->translate('Next page'); ?></span>
        </a>
    </p>
    <?php else:?>
    <p id="paginationNext">
        <?php echo $this->translate('Next page');?>
    </p>
    <?php endif;?>
    <div class="clearer"></div>
</div>
