<?php $comments = $this->recentCommentsWidget->getComments();?>

<?php if(count($comments)):?>
<div id="widget-<?php echo $this->recentCommentsWidget->getId();?>" class="box">
	<div class="boxHeader">
		<h1><?php echo $this->recentCommentsWidget->getTitle();?></h1>
	</div>
	<div class="boxBody">
		<ul>
			<?php foreach($comments as $comment):?>
			<li>
				<a href="/posts/view/id/<?php echo $comment['post_id'];?>" title="<?php echo $this->escape($comment['body']);?>">
					<span><?php echo $this->escape($comment['body']);?></span>
				</a>
			</li>
			<?php endforeach;?>
		</ul>
	</div>
	<div class="clearer"></div>
</div>
<?php endif;?>
